### ISSUE TITLE
[Feature] Client 개발 환경 구성 업데이트

### ISSUE THREAD

**Issue by seungsang00** [seungsang00/vanilaJS-SPA#2]
### ISSUE
- Group:  `Client`
- Type: `Update`
- Detail: Client 개발 환경 구성 업데이트

### TODO
- [ ] css-loader 적용
- [ ] html-webpack-plugin 적용
- [ ] webpack dev server 사용
